app:
  title: "ğŸ“¨ My Post Generator âœ¨"
  onboarding:
    - "## Welcome to ğŸ“¨ My Post Generator âœ¨"
    - ""
    - "This is a simple tool to generate your post."
  input: "ğŸ“ Enter the content for the post here ğŸ˜‰"
  upload: "ğŸ“ Upload the content for the post here ğŸ˜‰"
  rag:
    checkbox: "ğŸ“Œ Check this box if you want to generate a post with RAG (Retrieval Augment Generation)"
    input: "ğŸ’¡ Enter your question or focus for the post here ğŸ˜‰"
    search: "ğŸ” Search for the question or focus in the vector store ğŸ“š"
  select_box:
    instruction: "Select the tone of the post you want to generate"
    options:
      - "Captivating"
      - "Informative"
      - "Neutral"
  output: "Here will be your post ğŸ‰"
  submit: "Generate Post ğŸš€"
settings:
  extensions:
    - ".txt"
    - ".pdf"
vectordb:
  url: "4.157.220.93"
  localhost_ip: "0.0.0.0"
  port: 6333
